[package]
name = "avant-rbx/avant-runtime"
repository = "https://github.com/Avant-Rbx/Avant-Runtime"
description = "Runtime for running unit tests on Roblox."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "1.3.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["dist", "dist/*", "src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
NexusInstance = "thenexusavenger/nexus-instance@4.1.2"
TestEZ = "roblox/testez@0.4.1"
